spring.application.name=spring-boot-employment-platform

spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.cmypg58.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=jobportal